name = "Woodpile"
uuid = "7c292022-5c2a-4972-977a-05ecd640c8dd"
authors = ["Thomas Christensen <tchr@mit.edu> and contributors"]
version = "0.1.2"

[deps]
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
WoodpileMakieExt = ["Makie"]

[compat]
Makie = "0.22"
Meshing = "0.7"
StaticArrays = "1.9"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
